### ISSUE TITLE
[Bug]: Is conda-forge environment sufficiently constrained?

### ISSUE THREAD

**Issue by pochedls** [xCDAT/xcdat#237]
### Bug Report Criteria

- [X] Bug is not related to a data quality issue(s) beyond the scope of xCDAT
- [X] Bug is not related to core xarray APIs (please open an issue in the xarray repo if it is)

### What happened?

```
# create CDAT/xcdat environment (MacOS)
conda create -y -n cdat -c conda-forge -c cdat/label/v8.2.1 cdat "libnetcdf=*=mpi_openmpi_*" "mesalib=17.3.9" "python=3.7" xcdat

# activate environment
conda activate cdat

# execute python with single statement: "import xcdat"
python -c "import xcdat"
```

>  Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/pochedley1/miniconda3/envs/cdat/lib/python3.7/site-packages/xcdat/__init__.py", line 2, in <module>
>     from xcdat.axis import swap_lon_axis  # noqa: F401
>   File "/Users/pochedley1/miniconda3/envs/cdat/lib/python3.7/site-packages/xcdat/axis.py", line 3, in <module>
>     from typing import Dict, Literal, Optional, Tuple
> ImportError: cannot import name 'Literal' from 'typing' (/Users/pochedley1/miniconda3/envs/cdat/lib/python3.7/typing.py)

### What did you expect to happen?

Since the environment built, I expected to be able to execute both xcdat and CDAT without issue (this was possible in the past). 

I'm kind of confused...it [seems like](https://github.com/xCDAT/xcdat/blob/240e47ade4898fcb35ee9fa6baa473098c3e241f/setup.py) an environment should not be built with Python 3.7. 

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50)
[Clang 11.1.0 ]
python-bits: 64
OS: Darwin
OS-release: 19.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.20.2
pandas: 1.3.5
numpy: 1.21.6
scipy: 1.7.3
netCDF4: 1.5.6
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2022.02.0
distributed: 2022.02.0
matplotlib: 3.5.2
cartopy: None
seaborn: None
numbagg: None
fsspec: 2022.3.0
cupy: None
pint: None
sparse: None
setuptools: 59.8.0
pip: 22.1
conda: None
pytest: None
IPython: 7.33.0
sphinx: None

**Comment by tomvothecoder** [comment]
Thank you for reporting this @pochedls.

As noted from our exchange on Slack, `typing_extensions` is only need for Python < 3.8. However, those versions of Python are deprecated and 3.8 will soon be deprecated as well.

I will need to update the minimum Python version for `xcdat` to 3.8.
https://github.com/conda-forge/xcdat-feedstock/blob/5071957bd0d9c3a80ca20f73924722c4c94d877a/recipe/meta.yaml#L19-L23

I did notice in your example that your are explicitly installing Python 3.7.
```conda create -y -n cdat -c conda-forge -c cdat/label/v8.2.1 cdat "libnetcdf=*=mpi_openmpi_*" "mesalib=17.3.9" "python=3.7" xcdat```

Usually when you install a mix of packages, it will find the latest compatible versions of the common dependencies. In this case, I think conda will resolve Python to 3.9/3.10. Maybe give that a shot and see if the environment builds without dependency conflicts.

**Comment by pochedls** [comment]
Thanks @tomvothecoder. I had experimented with other setups, but it does _seem_ like dropping `python=3.7` creates an environment that works for both CDAT and xcdat. 

@jasonb5 - since python=3.7 is specified in the [CDAT install instructions](https://github.com/CDAT/cdat/wiki/install), do you see any issue with this?

**Comment by tomvothecoder** [comment]
This GH issue is related to package conflicts between the CDAT package and Python >3.8. 

Tests with CDAT and different Python versions:
---

CDAT + Python 3.8 -- **successfully builds**
```
conda create -y -n cdat_3.8 -c conda-forge -c cdat/label/v8.2.1 cdat "libnetcdf=*=mpi_openmpi_*" "mesalib=17.3.9" "python=3.8"
```

CDAT + Python 3.9 -- **package conflicts**
```
conda create -y -n cdat_3.9 -c conda-forge -c cdat/label/v8.2.1 cdat "libnetcdf=*=mpi_openmpi_*" "mesalib=17.3.9" "python=3.9"

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

CDAT + Python 3.10 -- **package conflicts**
```
conda create -y -n cdat_3.10 -c conda-forge -c cdat/label/v8.2.1 cdat "libnetcdf=*=mpi_openmpi_*" "mesalib=17.3.9" "python=3.10"

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

A problem with installing the entire CDAT package (per the instructions) vs. individual CDAT sub-packages is that there is a much higher chance of dependency conflicts. This is especially true with CDAT sub-packages who's dependencies aren't maintained. @jasonb5 can add to this.

The suggested alternative:
---

Install only the needed CDAT sub-packages for testing. A Python version (>=3.8) can be omitted and conda will chose the latest compatible version.
```
conda create -y -n cdat_xcdat -c conda-forge cdms2 cdutil genutil python=3.10 xcdat
```

**Tools such as E3SM diags and PMP list individual CDAT sub-packages as dependencies, rather than the CDAT package. This means package conflicts will be less of an issue in these tools. **

**Comment by bonfils2** [comment]
I tried: 
conda create -y -n cdat_xcdat -c conda-forge cdms2 cdutil genutil python=3.10 xcdat
It successfully builds, including making a plot with vcs plot and save it in .png. 
However, I tried to install nc-time-axis ("conda install -c conda-forge nc-time-axis") to plot the time series, and there are dependency conflicts.

With:
conda create -y -n cdat_3.8 -c conda-forge -c cdat/label/v8.2.1 cdat "libnetcdf=*=mpi_openmpi_*" "mesalib=17.3.9" "python=3.8"
I got back some vtk errors.

**Comment by bonfils2** [comment]
Thank you very much @pochedls and @tomvothecoder for all your help with this (from the ticket submission to possible solutions!) and for your prompt feedback.

**Comment by tomvothecoder** [comment]
Hi @bonfils2, I built the conda environment using the first command (`conda create -y -n cdat_xcdat -c conda-forge cdms2 cdutil genutil python=3.10 xcdat`) followed by `conda install -c conda-forge nc-time-axis` with success. I had no issues with dependency conflicts there.

I didn't try to second command (` conda create -y -n xcdat_test -c conda-forge -c cdat/label/v8.2.1 cdat xcdat "libnetcdf==nompi_" "mesalib=18.3.1" ipython`), but I wouldn't be surprised if dependency conflicts exist based on my previous comments in this GH issue.
