### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'xesmf' - using latest main 050d57e

### ISSUE THREAD

**Issue by durack1** [xCDAT/xcdat#306]
### What happened?

I am attempting to test the latest `main` branch following the guide at https://xcdat.readthedocs.io/en/stable/contributing.html#local-development, but am hitting the issue below:

```python
(xc030main220810) bash-4.2$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xcdat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~git/xcdat/xcdat/__init__.py", line 10, in <module>
    from xcdat.regridder.accessor import RegridderAccessor  # noqa: F401
  File "~/git/xcdat/xcdat/regridder/__init__.py", line 1, in <module>
    from xcdat.regridder.accessor import RegridderAccessor
  File "~/git/xcdat/xcdat/regridder/accessor.py", line 6, in <module>
    from xcdat.regridder import regrid2, xesmf
  File "~/git/xcdat/xcdat/regridder/xesmf.py", line 2, in <module>
    import xesmf as xe
ModuleNotFoundError: No module named 'xesmf'
>>>
(xc030main220810) bash-4.2$ pwd
~/git/xcdat
(xc030main220810) bash-4.2$ git rev-parse --short HEAD
050d57e
```

### What did you expect to happen?

I expected `xcdat` to load successfully

### Minimal Complete Verifiable Example

```python
(base) bash-4.2$ pwd
~/git/xcdat
(base) bash-4.2$ git fetch –all -p
(base) bash-4.2$ git checkout main
(base) bash-4.2$ git pull
(base) bash-4.2$ conda env create -f conda-env/dev.yml
(base) bash-4.2$ conda activate xcdat_dev
(xcdat_dev) bash-4.2$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xcdat
```

And for a sanity check, looks like the hashes checkout
```python
(xcdat_dev) bash-4.2$ git rev-parse --short HEAD
050d57e
```

Which matches the current `main` https://github.com/xCDAT/xcdat/commit/050d57edc591b78480c14ea0e581391b00fe23b1

### Relevant log output

```python
>>> import xcdat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~git/xcdat/xcdat/__init__.py", line 10, in <module>
    from xcdat.regridder.accessor import RegridderAccessor  # noqa: F401
  File "~/git/xcdat/xcdat/regridder/__init__.py", line 1, in <module>
    from xcdat.regridder.accessor import RegridderAccessor
  File "~/git/xcdat/xcdat/regridder/accessor.py", line 6, in <module>
    from xcdat.regridder import regrid2, xesmf
  File "~/git/xcdat/xcdat/regridder/xesmf.py", line 2, in <module>
    import xesmf as xe
ModuleNotFoundError: No module named 'xesmf'
```

### Anything else we need to know?

I believe this is occurring across multiple users @pochedls can confirm?

### Environment

```python
(xcdat_dev) bash-4.2$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray as xr
i>>> xr.show_versions()
~/mambaforge/envs/xcdat_dev/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.62.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 2022.3.0
pandas: 1.4.3
numpy: 1.22.4
scipy: None
netCDF4: 1.5.8
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2022.6.1
distributed: 2022.6.1
matplotlib: 3.5.2
cartopy: None
seaborn: None
numbagg: None
fsspec: 2022.7.1
cupy: None
pint: None
sparse: None
setuptools: 63.4.2
pip: 22.1.2
conda: None
pytest: 7.1.2
IPython: 7.33.0
sphinx: 4.5.0
```

**Comment by tomvothecoder** [comment]
Thanks @durack1, I think we accidentally removed `xesmf` from the [`dev.yml`](https://github.com/xCDAT/xcdat/blob/main/conda-env/dev.yml) file due to rebasing on one of the recent PRs.

I ran into the same issue and added `xesmf` back in this PR: https://github.com/xCDAT/xcdat/pull/302/files#diff-8349720d2c3c13b89033622dc7617e89cdc970177deed2f40c2dc84c52562224

I will make a separate PR specifically for this fix though, will roll it out ASAP.

**Comment by durack1** [comment]
@tomvothecoder thanks for the quick reply, will await the merge and give it another go when it's live

**Comment by durack1** [comment]
@tomvothecoder just pulled down the latest main https://github.com/xCDAT/xcdat/commit/1d242e5dc248873cf570bc77b01f5e6f0069a98e, and I am all fixed

```python
(base) bash-4.2$ conda activate xc030main2208101245
(xc030main2208101245) bash-4.2$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xcdat
>>>
```

Thanks for the prompt turnaround

**Comment by durack1** [comment]
@tomvothecoder I just took a peek at [conda-env/dev.yml](https://github.com/xCDAT/xcdat/blob/main/conda-env/dev.yml) and it seems that `xcdat` is not listed, is that expected?

It seems that `xcdat` isn't listed in the env `conda-meta` subdir:
```python
bash-4.2$ ls -1 ~/mambaforge/envs/xc030main2208101245/conda-meta/xc*
~/mambaforge/envs/xc030main2208101245/conda-meta/xcb-util-0.4.0-h166bdaf_0.json
~/mambaforge/envs/xc030main2208101245/conda-meta/xcb-util-image-0.4.0-h166bdaf_0.json
~/mambaforge/envs/xc030main2208101245/conda-meta/xcb-util-keysyms-0.4.0-h166bdaf_0.json
~/mambaforge/envs/xc030main2208101245/conda-meta/xcb-util-renderutil-0.3.9-h166bdaf_0.json
~/mambaforge/envs/xc030main2208101245/conda-meta/xcb-util-wm-0.4.1-h166bdaf_0.json
```
Weirdly, it seems that the test above https://github.com/xCDAT/xcdat/issues/306#issuecomment-1211197113 did load the module, but I am unsure where from

**Comment by durack1** [comment]
@tomvothecoder no idea what is happening, this didn't work on a second pass
```python
(base) bash-4.2$ conda activate xc030main2208101245
(xc030main2208101245) bash-4.2$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import xcdat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'xcdat'
```

**Comment by tomvothecoder** [comment]
> @tomvothecoder I just took a peek at [conda-env/dev.yml](https://github.com/xCDAT/xcdat/blob/main/conda-env/dev.yml?rgh-link-date=2022-08-10T20%3A31%3A50Z) and it seems that xcdat is not listed, is that expected?

@durack1 Yes that is expected. Since this is the development environment, `import xcdat` uses the local `xcdat` directory 
(https://github.com/xCDAT/xcdat/tree/main/xcdat) so that changes are reloaded on the fly using, rather than needing to `pip install .` the local build of the package. 

We don't want to list `xcdat` in the `dev.yml` because it will use the latest release on conda-forge instead.

> @tomvothecoder no idea what is happening, this didn't work on a second pass

Are you running `python` and `import xcdat` from the root directory of the repository? If not, I don't think Python can find the local `xcdat` directory.

**Comment by durack1** [comment]
@tomvothecoder sorry about the noob questions here. My issue is getting `spyder` (which is installed into the same env) to recognize the local xcdat - that is my problem.

So to clarify, the local path (xcdat_dev) $ python (commandline) can find xcdat, but (xcdat_dev) $ spyder (installed into the same env, which has all the env modules available) doesn't. This is an issue with spyder...

**Comment by pochedls** [comment]
What directory are you in when using Spyder? If you are not in the xcdat dev directory, you can add it via PYTHONPATH (in bash) or via `import sys; sys.path.append('/path/to/xcdat/')`

**Comment by durack1** [comment]
@pochedls, it's a little more complex than that; I **think** that the lack of inclusion in the `site-packages` subdir is my issue
```python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
Type "copyright", "credits" or "license" for more information.
IPython 7.33.0 -- An enhanced Interactive Python.

import sys
sys.path
Out[2]: 
['~/mambaforge/envs/xc030main2208101245/lib/python39.zip',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9/lib-dynload',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9/site-packages',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9/site-packages/IPython/extensions',
 '~/.ipython']

sys.path.append("~/git/xcdat/xcdat")

import xcdat
Traceback (most recent call last):

  File "/tmp/ipykernel_16798/2264195919.py", line 1, in <cell line: 1>
    import xcdat

ModuleNotFoundError: No module named 'xcdat'

sys.path
Out[8]: 
['~/mambaforge/envs/xc030main2208101245/lib/python39.zip',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9/lib-dynload',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9/site-packages',
 '/~/mambaforge/envs/xc030main2208101245/lib/python3.9/site-packages/IPython/extensions',
 '~/.ipython',
 '~/git/xcdat/xcdat']
```

I'll have to figure out how to wedge another path into the `ipython` look ups

**Comment by durack1** [comment]
@pochedls, you know `spyder` better than I know `spyder`. Tips below for fellow noobers like me

```python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
Type "copyright", "credits" or "license" for more information.

IPython 7.33.0 -- An enhanced Interactive Python.

In [1]: import os, sys
In [2]: os.getcwd()
Out[2]: '~'
In [3]: sys.path
Out[3]: 
['~/mambaforge/envs/xc030main2208101245/lib/python39.zip',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9/lib-dynload',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9/site-packages',
 '~/mambaforge/envs/xc030main2208101245/lib/python3.9/site-packages/IPython/extensions',
 '~/.ipython']
In [4]: os.chdir("~/git/xcdat")
In [5]: os.getcwd()
Out[5]: '~/git/xcdat'
In [6]: import xcdat
In [7]: 
```
