### ISSUE TITLE
[Bug]: Regrid does not preserve attributes

### ISSUE THREAD

**Issue by lee1043** [xCDAT/xcdat#445]
### What happened?

After `ds.regridder.horizontal` process, attributions (e.g., units) are not preserved. 

### What did you expect to happen?

To be preserved.

### Minimal Complete Verifiable Example

```python
>>> ds = xc.open_dataset('/work/lee1043/cdat/pmp/E3SM/E3SMv3_evaluation/mean_climate/clim/clim/cmip6.historical.E3SMv3.r1i1p1f1.mon.pr.198101-200512.AC.v20230404.nc')
>>> ds['pr'].units
'kg m-2 s-1'
>>> t_grid = xc.create_uniform_grid(-88.875, 88.625, 2.5, 0, 357.5, 2.5)
>>> varname = 'pr'
>>> ds_regridded = ds.regridder.horizontal(varname, t_grid, tool='regrid2')
>>> ds_regridded[varname].attrs
{}
>>> ds_regridded['pr'].units
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lee1043/.conda/envs/pcmdi_metrics_dev_20230201/lib/python3.9/site-packages/xarray/core/common.py", line 278, in __getattr__
    raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'units'
```
```


### Relevant log output

_No response_

### Anything else we need to know?

_No response_

### Environment

xCDAT 0.5.0

**Comment by jasonb5** [comment]
@lee1043 If possible could you provide a link to the source file?

**Comment by lee1043** [comment]
@jasonb5 Thank you for taking this a look. I noticed the directory path slightly changed since then. Would you be able to access below file from the gates? Otherwise I will email or upload it.

/work/lee1043/cdat/pmp/E3SM/E3SMv3_evaluation/mean_climate/clim/cmip6.historical.E3SMv3.r1i1p1f1.mon.pr.198101-200512.AC.v20230404.nc

**Comment by jasonb5** [comment]
Found the issue, will have a PR soon. Regrid2 is creating the dataarray from scratch and not copying the attributes from the source dataarray, we do copy the dataset attributes.
